//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNueva.ServiciosWCF.Catalogo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticuloCategoriaCatalogoWebData", Namespace="http://schemas.datacontract.org/2004/07/Nubian.Servicios.Web.Catalogo.Contracts")]
    [System.SerializableAttribute()]
    public partial class ArticuloCategoriaCatalogoWebData : AppNueva.ServiciosWCF.Catalogo.EntidadIdentificable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlImagenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlImagen {
            get {
                return this.UrlImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlImagenField, value) != true)) {
                    this.UrlImagenField = value;
                    this.RaisePropertyChanged("UrlImagen");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadIdentificable", Namespace="http://schemas.datacontract.org/2004/07/Nubian.Servicios.Genericos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppNueva.ServiciosWCF.Catalogo.ArticuloCatalogoWebData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppNueva.ServiciosWCF.Catalogo.ArticuloColorCatalogoWebData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppNueva.ServiciosWCF.Catalogo.ArticuloWebData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppNueva.ServiciosWCF.Catalogo.ArticuloColorWebData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppNueva.ServiciosWCF.Catalogo.ArticuloCategoriaCatalogoWebData))]
    public partial class EntidadIdentificable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_TemporalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Temporal {
            get {
                return this.Id_TemporalField;
            }
            set {
                if ((this.Id_TemporalField.Equals(value) != true)) {
                    this.Id_TemporalField = value;
                    this.RaisePropertyChanged("Id_Temporal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticuloCatalogoWebData", Namespace="http://schemas.datacontract.org/2004/07/Nubian.Servicios.Web.Catalogo.Contracts")]
    [System.SerializableAttribute()]
    public partial class ArticuloCatalogoWebData : AppNueva.ServiciosWCF.Catalogo.EntidadIdentificable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BordeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedidasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MezclaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlImagenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Borde {
            get {
                return this.BordeField;
            }
            set {
                if ((object.ReferenceEquals(this.BordeField, value) != true)) {
                    this.BordeField = value;
                    this.RaisePropertyChanged("Borde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCompleto {
            get {
                return this.CodigoCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoCompletoField, value) != true)) {
                    this.CodigoCompletoField = value;
                    this.RaisePropertyChanged("CodigoCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Medidas {
            get {
                return this.MedidasField;
            }
            set {
                if ((object.ReferenceEquals(this.MedidasField, value) != true)) {
                    this.MedidasField = value;
                    this.RaisePropertyChanged("Medidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mezcla {
            get {
                return this.MezclaField;
            }
            set {
                if ((object.ReferenceEquals(this.MezclaField, value) != true)) {
                    this.MezclaField = value;
                    this.RaisePropertyChanged("Mezcla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pelo {
            get {
                return this.PeloField;
            }
            set {
                if ((this.PeloField.Equals(value) != true)) {
                    this.PeloField = value;
                    this.RaisePropertyChanged("Pelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Peso {
            get {
                return this.PesoField;
            }
            set {
                if ((this.PesoField.Equals(value) != true)) {
                    this.PesoField = value;
                    this.RaisePropertyChanged("Peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlImagen {
            get {
                return this.UrlImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlImagenField, value) != true)) {
                    this.UrlImagenField = value;
                    this.RaisePropertyChanged("UrlImagen");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticuloColorCatalogoWebData", Namespace="http://schemas.datacontract.org/2004/07/Nubian.Servicios.Web.Catalogo.Contracts")]
    [System.SerializableAttribute()]
    public partial class ArticuloColorCatalogoWebData : AppNueva.ServiciosWCF.Catalogo.EntidadIdentificable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorReferencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoresTramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoresUrdimbreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPublicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlImagenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorReferencial {
            get {
                return this.ColorReferencialField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorReferencialField, value) != true)) {
                    this.ColorReferencialField = value;
                    this.RaisePropertyChanged("ColorReferencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColoresTrama {
            get {
                return this.ColoresTramaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoresTramaField, value) != true)) {
                    this.ColoresTramaField = value;
                    this.RaisePropertyChanged("ColoresTrama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColoresUrdimbre {
            get {
                return this.ColoresUrdimbreField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoresUrdimbreField, value) != true)) {
                    this.ColoresUrdimbreField = value;
                    this.RaisePropertyChanged("ColoresUrdimbre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPublicacion {
            get {
                return this.FechaPublicacionField;
            }
            set {
                if ((this.FechaPublicacionField.Equals(value) != true)) {
                    this.FechaPublicacionField = value;
                    this.RaisePropertyChanged("FechaPublicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nro {
            get {
                return this.NroField;
            }
            set {
                if ((this.NroField.Equals(value) != true)) {
                    this.NroField = value;
                    this.RaisePropertyChanged("Nro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlImagen {
            get {
                return this.UrlImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlImagenField, value) != true)) {
                    this.UrlImagenField = value;
                    this.RaisePropertyChanged("UrlImagen");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticuloWebData", Namespace="http://schemas.datacontract.org/2004/07/Nubian.Servicios.Web.Catalogo.Contracts")]
    [System.SerializableAttribute()]
    public partial class ArticuloWebData : AppNueva.ServiciosWCF.Catalogo.EntidadIdentificable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcronimoCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnchoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArticuloCategoria_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BordeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FlecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MezclaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoFlecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcronimoCategoria {
            get {
                return this.AcronimoCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.AcronimoCategoriaField, value) != true)) {
                    this.AcronimoCategoriaField = value;
                    this.RaisePropertyChanged("AcronimoCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ancho {
            get {
                return this.AnchoField;
            }
            set {
                if ((this.AnchoField.Equals(value) != true)) {
                    this.AnchoField = value;
                    this.RaisePropertyChanged("Ancho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArticuloCategoria_Id {
            get {
                return this.ArticuloCategoria_IdField;
            }
            set {
                if ((this.ArticuloCategoria_IdField.Equals(value) != true)) {
                    this.ArticuloCategoria_IdField = value;
                    this.RaisePropertyChanged("ArticuloCategoria_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Borde {
            get {
                return this.BordeField;
            }
            set {
                if ((object.ReferenceEquals(this.BordeField, value) != true)) {
                    this.BordeField = value;
                    this.RaisePropertyChanged("Borde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Fleco {
            get {
                return this.FlecoField;
            }
            set {
                if ((this.FlecoField.Equals(value) != true)) {
                    this.FlecoField = value;
                    this.RaisePropertyChanged("Fleco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Largo {
            get {
                return this.LargoField;
            }
            set {
                if ((this.LargoField.Equals(value) != true)) {
                    this.LargoField = value;
                    this.RaisePropertyChanged("Largo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mezcla {
            get {
                return this.MezclaField;
            }
            set {
                if ((object.ReferenceEquals(this.MezclaField, value) != true)) {
                    this.MezclaField = value;
                    this.RaisePropertyChanged("Mezcla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nro {
            get {
                return this.NroField;
            }
            set {
                if ((this.NroField.Equals(value) != true)) {
                    this.NroField = value;
                    this.RaisePropertyChanged("Nro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pelo {
            get {
                return this.PeloField;
            }
            set {
                if ((this.PeloField.Equals(value) != true)) {
                    this.PeloField = value;
                    this.RaisePropertyChanged("Pelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Peso {
            get {
                return this.PesoField;
            }
            set {
                if ((this.PesoField.Equals(value) != true)) {
                    this.PesoField = value;
                    this.RaisePropertyChanged("Peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoFleco {
            get {
                return this.TipoFlecoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoFlecoField, value) != true)) {
                    this.TipoFlecoField = value;
                    this.RaisePropertyChanged("TipoFleco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticuloColorWebData", Namespace="http://schemas.datacontract.org/2004/07/Nubian.Servicios.Web.Catalogo.Contracts")]
    [System.SerializableAttribute()]
    public partial class ArticuloColorWebData : AppNueva.ServiciosWCF.Catalogo.EntidadIdentificable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Articulo_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorReferencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoresTramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoresTramaConLeyendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoresUrdimbreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoresUrdimbreConLeyendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPublicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Articulo_Id {
            get {
                return this.Articulo_IdField;
            }
            set {
                if ((this.Articulo_IdField.Equals(value) != true)) {
                    this.Articulo_IdField = value;
                    this.RaisePropertyChanged("Articulo_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorReferencial {
            get {
                return this.ColorReferencialField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorReferencialField, value) != true)) {
                    this.ColorReferencialField = value;
                    this.RaisePropertyChanged("ColorReferencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColoresTrama {
            get {
                return this.ColoresTramaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoresTramaField, value) != true)) {
                    this.ColoresTramaField = value;
                    this.RaisePropertyChanged("ColoresTrama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColoresTramaConLeyenda {
            get {
                return this.ColoresTramaConLeyendaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoresTramaConLeyendaField, value) != true)) {
                    this.ColoresTramaConLeyendaField = value;
                    this.RaisePropertyChanged("ColoresTramaConLeyenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColoresUrdimbre {
            get {
                return this.ColoresUrdimbreField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoresUrdimbreField, value) != true)) {
                    this.ColoresUrdimbreField = value;
                    this.RaisePropertyChanged("ColoresUrdimbre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColoresUrdimbreConLeyenda {
            get {
                return this.ColoresUrdimbreConLeyendaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoresUrdimbreConLeyendaField, value) != true)) {
                    this.ColoresUrdimbreConLeyendaField = value;
                    this.RaisePropertyChanged("ColoresUrdimbreConLeyenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPublicacion {
            get {
                return this.FechaPublicacionField;
            }
            set {
                if ((this.FechaPublicacionField.Equals(value) != true)) {
                    this.FechaPublicacionField = value;
                    this.RaisePropertyChanged("FechaPublicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nro {
            get {
                return this.NroField;
            }
            set {
                if ((this.NroField.Equals(value) != true)) {
                    this.NroField = value;
                    this.RaisePropertyChanged("Nro");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoInicioSesionUsuarioWeb", Namespace="http://schemas.datacontract.org/2004/07/Nubian.Servicios.Web.Catalogo.Contracts")]
    [System.SerializableAttribute()]
    public partial class InfoInicioSesionUsuarioWeb : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PuedeVerInventarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PuedeVerInventario {
            get {
                return this.PuedeVerInventarioField;
            }
            set {
                if ((this.PuedeVerInventarioField.Equals(value) != true)) {
                    this.PuedeVerInventarioField = value;
                    this.RaisePropertyChanged("PuedeVerInventario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosWCF.Catalogo.ICatalogoService")]
    public interface ICatalogoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Obtener_Categorias", ReplyAction="http://tempuri.org/ICatalogoService/Obtener_CategoriasResponse")]
        AppNueva.ServiciosWCF.Catalogo.ArticuloCategoriaCatalogoWebData[] Obtener_Categorias(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Obtener_Categorias", ReplyAction="http://tempuri.org/ICatalogoService/Obtener_CategoriasResponse")]
        System.Threading.Tasks.Task<AppNueva.ServiciosWCF.Catalogo.ArticuloCategoriaCatalogoWebData[]> Obtener_CategoriasAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Obtener_ArticulosPorCategoria", ReplyAction="http://tempuri.org/ICatalogoService/Obtener_ArticulosPorCategoriaResponse")]
        AppNueva.ServiciosWCF.Catalogo.ArticuloCatalogoWebData[] Obtener_ArticulosPorCategoria(int Id_Categoria, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Obtener_ArticulosPorCategoria", ReplyAction="http://tempuri.org/ICatalogoService/Obtener_ArticulosPorCategoriaResponse")]
        System.Threading.Tasks.Task<AppNueva.ServiciosWCF.Catalogo.ArticuloCatalogoWebData[]> Obtener_ArticulosPorCategoriaAsync(int Id_Categoria, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Obtener_ColoresPorArticulo", ReplyAction="http://tempuri.org/ICatalogoService/Obtener_ColoresPorArticuloResponse")]
        AppNueva.ServiciosWCF.Catalogo.ArticuloColorCatalogoWebData[] Obtener_ColoresPorArticulo(int Id_Articulo, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Obtener_ColoresPorArticulo", ReplyAction="http://tempuri.org/ICatalogoService/Obtener_ColoresPorArticuloResponse")]
        System.Threading.Tasks.Task<AppNueva.ServiciosWCF.Catalogo.ArticuloColorCatalogoWebData[]> Obtener_ColoresPorArticuloAsync(int Id_Articulo, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Obtener_IdsArticulosExistentesPorIdCategoria", ReplyAction="http://tempuri.org/ICatalogoService/Obtener_IdsArticulosExistentesPorIdCategoriaR" +
            "esponse")]
        int[] Obtener_IdsArticulosExistentesPorIdCategoria(int Id_Categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Obtener_IdsArticulosExistentesPorIdCategoria", ReplyAction="http://tempuri.org/ICatalogoService/Obtener_IdsArticulosExistentesPorIdCategoriaR" +
            "esponse")]
        System.Threading.Tasks.Task<int[]> Obtener_IdsArticulosExistentesPorIdCategoriaAsync(int Id_Categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Obtener_IdsArticulosExistentes", ReplyAction="http://tempuri.org/ICatalogoService/Obtener_IdsArticulosExistentesResponse")]
        int[] Obtener_IdsArticulosExistentes(int[] Ids_Articulos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Obtener_IdsArticulosExistentes", ReplyAction="http://tempuri.org/ICatalogoService/Obtener_IdsArticulosExistentesResponse")]
        System.Threading.Tasks.Task<int[]> Obtener_IdsArticulosExistentesAsync(int[] Ids_Articulos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Obtener_IdsColoresPorArticulo", ReplyAction="http://tempuri.org/ICatalogoService/Obtener_IdsColoresPorArticuloResponse")]
        int[] Obtener_IdsColoresPorArticulo(int Id_Articulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Obtener_IdsColoresPorArticulo", ReplyAction="http://tempuri.org/ICatalogoService/Obtener_IdsColoresPorArticuloResponse")]
        System.Threading.Tasks.Task<int[]> Obtener_IdsColoresPorArticuloAsync(int Id_Articulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Nuevo_Articulo", ReplyAction="http://tempuri.org/ICatalogoService/Nuevo_ArticuloResponse")]
        void Nuevo_Articulo(AppNueva.ServiciosWCF.Catalogo.ArticuloWebData articulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Nuevo_Articulo", ReplyAction="http://tempuri.org/ICatalogoService/Nuevo_ArticuloResponse")]
        System.Threading.Tasks.Task Nuevo_ArticuloAsync(AppNueva.ServiciosWCF.Catalogo.ArticuloWebData articulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Nuevo_Color", ReplyAction="http://tempuri.org/ICatalogoService/Nuevo_ColorResponse")]
        void Nuevo_Color(AppNueva.ServiciosWCF.Catalogo.ArticuloColorWebData[] colores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Nuevo_Color", ReplyAction="http://tempuri.org/ICatalogoService/Nuevo_ColorResponse")]
        System.Threading.Tasks.Task Nuevo_ColorAsync(AppNueva.ServiciosWCF.Catalogo.ArticuloColorWebData[] colores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Eliminar_Articulos", ReplyAction="http://tempuri.org/ICatalogoService/Eliminar_ArticulosResponse")]
        void Eliminar_Articulos(int[] Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Eliminar_Articulos", ReplyAction="http://tempuri.org/ICatalogoService/Eliminar_ArticulosResponse")]
        System.Threading.Tasks.Task Eliminar_ArticulosAsync(int[] Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Eliminar_Colores", ReplyAction="http://tempuri.org/ICatalogoService/Eliminar_ColoresResponse")]
        void Eliminar_Colores(int[] Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Eliminar_Colores", ReplyAction="http://tempuri.org/ICatalogoService/Eliminar_ColoresResponse")]
        System.Threading.Tasks.Task Eliminar_ColoresAsync(int[] Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Iniciar_Sesion", ReplyAction="http://tempuri.org/ICatalogoService/Iniciar_SesionResponse")]
        AppNueva.ServiciosWCF.Catalogo.InfoInicioSesionUsuarioWeb Iniciar_Sesion(string Correo, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoService/Iniciar_Sesion", ReplyAction="http://tempuri.org/ICatalogoService/Iniciar_SesionResponse")]
        System.Threading.Tasks.Task<AppNueva.ServiciosWCF.Catalogo.InfoInicioSesionUsuarioWeb> Iniciar_SesionAsync(string Correo, string Clave);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogoServiceChannel : AppNueva.ServiciosWCF.Catalogo.ICatalogoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogoServiceClient : System.ServiceModel.ClientBase<AppNueva.ServiciosWCF.Catalogo.ICatalogoService>, AppNueva.ServiciosWCF.Catalogo.ICatalogoService {
        
        public CatalogoServiceClient() {
        }
        
        public CatalogoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppNueva.ServiciosWCF.Catalogo.ArticuloCategoriaCatalogoWebData[] Obtener_Categorias(string token) {
            return base.Channel.Obtener_Categorias(token);
        }
        
        public System.Threading.Tasks.Task<AppNueva.ServiciosWCF.Catalogo.ArticuloCategoriaCatalogoWebData[]> Obtener_CategoriasAsync(string token) {
            return base.Channel.Obtener_CategoriasAsync(token);
        }
        
        public AppNueva.ServiciosWCF.Catalogo.ArticuloCatalogoWebData[] Obtener_ArticulosPorCategoria(int Id_Categoria, string token) {
            return base.Channel.Obtener_ArticulosPorCategoria(Id_Categoria, token);
        }
        
        public System.Threading.Tasks.Task<AppNueva.ServiciosWCF.Catalogo.ArticuloCatalogoWebData[]> Obtener_ArticulosPorCategoriaAsync(int Id_Categoria, string token) {
            return base.Channel.Obtener_ArticulosPorCategoriaAsync(Id_Categoria, token);
        }
        
        public AppNueva.ServiciosWCF.Catalogo.ArticuloColorCatalogoWebData[] Obtener_ColoresPorArticulo(int Id_Articulo, string token) {
            return base.Channel.Obtener_ColoresPorArticulo(Id_Articulo, token);
        }
        
        public System.Threading.Tasks.Task<AppNueva.ServiciosWCF.Catalogo.ArticuloColorCatalogoWebData[]> Obtener_ColoresPorArticuloAsync(int Id_Articulo, string token) {
            return base.Channel.Obtener_ColoresPorArticuloAsync(Id_Articulo, token);
        }
        
        public int[] Obtener_IdsArticulosExistentesPorIdCategoria(int Id_Categoria) {
            return base.Channel.Obtener_IdsArticulosExistentesPorIdCategoria(Id_Categoria);
        }
        
        public System.Threading.Tasks.Task<int[]> Obtener_IdsArticulosExistentesPorIdCategoriaAsync(int Id_Categoria) {
            return base.Channel.Obtener_IdsArticulosExistentesPorIdCategoriaAsync(Id_Categoria);
        }
        
        public int[] Obtener_IdsArticulosExistentes(int[] Ids_Articulos) {
            return base.Channel.Obtener_IdsArticulosExistentes(Ids_Articulos);
        }
        
        public System.Threading.Tasks.Task<int[]> Obtener_IdsArticulosExistentesAsync(int[] Ids_Articulos) {
            return base.Channel.Obtener_IdsArticulosExistentesAsync(Ids_Articulos);
        }
        
        public int[] Obtener_IdsColoresPorArticulo(int Id_Articulo) {
            return base.Channel.Obtener_IdsColoresPorArticulo(Id_Articulo);
        }
        
        public System.Threading.Tasks.Task<int[]> Obtener_IdsColoresPorArticuloAsync(int Id_Articulo) {
            return base.Channel.Obtener_IdsColoresPorArticuloAsync(Id_Articulo);
        }
        
        public void Nuevo_Articulo(AppNueva.ServiciosWCF.Catalogo.ArticuloWebData articulo) {
            base.Channel.Nuevo_Articulo(articulo);
        }
        
        public System.Threading.Tasks.Task Nuevo_ArticuloAsync(AppNueva.ServiciosWCF.Catalogo.ArticuloWebData articulo) {
            return base.Channel.Nuevo_ArticuloAsync(articulo);
        }
        
        public void Nuevo_Color(AppNueva.ServiciosWCF.Catalogo.ArticuloColorWebData[] colores) {
            base.Channel.Nuevo_Color(colores);
        }
        
        public System.Threading.Tasks.Task Nuevo_ColorAsync(AppNueva.ServiciosWCF.Catalogo.ArticuloColorWebData[] colores) {
            return base.Channel.Nuevo_ColorAsync(colores);
        }
        
        public void Eliminar_Articulos(int[] Ids) {
            base.Channel.Eliminar_Articulos(Ids);
        }
        
        public System.Threading.Tasks.Task Eliminar_ArticulosAsync(int[] Ids) {
            return base.Channel.Eliminar_ArticulosAsync(Ids);
        }
        
        public void Eliminar_Colores(int[] Ids) {
            base.Channel.Eliminar_Colores(Ids);
        }
        
        public System.Threading.Tasks.Task Eliminar_ColoresAsync(int[] Ids) {
            return base.Channel.Eliminar_ColoresAsync(Ids);
        }
        
        public AppNueva.ServiciosWCF.Catalogo.InfoInicioSesionUsuarioWeb Iniciar_Sesion(string Correo, string Clave) {
            return base.Channel.Iniciar_Sesion(Correo, Clave);
        }
        
        public System.Threading.Tasks.Task<AppNueva.ServiciosWCF.Catalogo.InfoInicioSesionUsuarioWeb> Iniciar_SesionAsync(string Correo, string Clave) {
            return base.Channel.Iniciar_SesionAsync(Correo, Clave);
        }
    }
}
