//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNueva.ServiciosWCF.Mensajes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MensajeWebData", Namespace="http://schemas.datacontract.org/2004/07/Nubian.Servicios.Web.Mensajes.Contracts")]
    [System.SerializableAttribute()]
    public partial class MensajeWebData : AppNueva.ServiciosWCF.Mensajes.EntidadIdentificable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresApellidosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombresApellidos {
            get {
                return this.NombresApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresApellidosField, value) != true)) {
                    this.NombresApellidosField = value;
                    this.RaisePropertyChanged("NombresApellidos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadIdentificable", Namespace="http://schemas.datacontract.org/2004/07/Nubian.Servicios.Genericos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppNueva.ServiciosWCF.Mensajes.MensajeWebData))]
    public partial class EntidadIdentificable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_TemporalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Temporal {
            get {
                return this.Id_TemporalField;
            }
            set {
                if ((this.Id_TemporalField.Equals(value) != true)) {
                    this.Id_TemporalField = value;
                    this.RaisePropertyChanged("Id_Temporal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosWCF.Mensajes.IMensajesWebService")]
    public interface IMensajesWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajesWebService/Obtener_MensajesWeb", ReplyAction="http://tempuri.org/IMensajesWebService/Obtener_MensajesWebResponse")]
        AppNueva.ServiciosWCF.Mensajes.MensajeWebData[] Obtener_MensajesWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajesWebService/Obtener_MensajesWeb", ReplyAction="http://tempuri.org/IMensajesWebService/Obtener_MensajesWebResponse")]
        System.Threading.Tasks.Task<AppNueva.ServiciosWCF.Mensajes.MensajeWebData[]> Obtener_MensajesWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajesWebService/Obtener_NroMensajesWebExistentes", ReplyAction="http://tempuri.org/IMensajesWebService/Obtener_NroMensajesWebExistentesResponse")]
        int Obtener_NroMensajesWebExistentes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajesWebService/Obtener_NroMensajesWebExistentes", ReplyAction="http://tempuri.org/IMensajesWebService/Obtener_NroMensajesWebExistentesResponse")]
        System.Threading.Tasks.Task<int> Obtener_NroMensajesWebExistentesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajesWebService/Nuevo_MensajeWeb", ReplyAction="http://tempuri.org/IMensajesWebService/Nuevo_MensajeWebResponse")]
        void Nuevo_MensajeWeb(string NombresApeliidos, string Correo, string Mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajesWebService/Nuevo_MensajeWeb", ReplyAction="http://tempuri.org/IMensajesWebService/Nuevo_MensajeWebResponse")]
        System.Threading.Tasks.Task Nuevo_MensajeWebAsync(string NombresApeliidos, string Correo, string Mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajesWebService/Eliminar_MensajesWeb", ReplyAction="http://tempuri.org/IMensajesWebService/Eliminar_MensajesWebResponse")]
        void Eliminar_MensajesWeb(int[] Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajesWebService/Eliminar_MensajesWeb", ReplyAction="http://tempuri.org/IMensajesWebService/Eliminar_MensajesWebResponse")]
        System.Threading.Tasks.Task Eliminar_MensajesWebAsync(int[] Ids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMensajesWebServiceChannel : AppNueva.ServiciosWCF.Mensajes.IMensajesWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MensajesWebServiceClient : System.ServiceModel.ClientBase<AppNueva.ServiciosWCF.Mensajes.IMensajesWebService>, AppNueva.ServiciosWCF.Mensajes.IMensajesWebService {
        
        public MensajesWebServiceClient() {
        }
        
        public MensajesWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MensajesWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MensajesWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MensajesWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppNueva.ServiciosWCF.Mensajes.MensajeWebData[] Obtener_MensajesWeb() {
            return base.Channel.Obtener_MensajesWeb();
        }
        
        public System.Threading.Tasks.Task<AppNueva.ServiciosWCF.Mensajes.MensajeWebData[]> Obtener_MensajesWebAsync() {
            return base.Channel.Obtener_MensajesWebAsync();
        }
        
        public int Obtener_NroMensajesWebExistentes() {
            return base.Channel.Obtener_NroMensajesWebExistentes();
        }
        
        public System.Threading.Tasks.Task<int> Obtener_NroMensajesWebExistentesAsync() {
            return base.Channel.Obtener_NroMensajesWebExistentesAsync();
        }
        
        public void Nuevo_MensajeWeb(string NombresApeliidos, string Correo, string Mensaje) {
            base.Channel.Nuevo_MensajeWeb(NombresApeliidos, Correo, Mensaje);
        }
        
        public System.Threading.Tasks.Task Nuevo_MensajeWebAsync(string NombresApeliidos, string Correo, string Mensaje) {
            return base.Channel.Nuevo_MensajeWebAsync(NombresApeliidos, Correo, Mensaje);
        }
        
        public void Eliminar_MensajesWeb(int[] Ids) {
            base.Channel.Eliminar_MensajesWeb(Ids);
        }
        
        public System.Threading.Tasks.Task Eliminar_MensajesWebAsync(int[] Ids) {
            return base.Channel.Eliminar_MensajesWebAsync(Ids);
        }
    }
}
